### ISSUE TITLE
(New) section not affected by theme

### ISSUE THREAD

**Issue by livinhack** [eriroh/Mainsail-x-Voron-Toolhead-Theme#3]
In the current Mainsail version, under "Machine" there is a "System load" field.

The text in it (apart from Host) is not captured by the **theme** and thus remains black on a gray background.

Is it possible to fix this?

Thanks

Screenshot:
![theme](https://user-images.githubusercontent.com/91290219/176992399-a0330c89-7e7b-4c8d-952c-3ae399c39151.JPG)

**Comment by eriroh** [comment]
Thanks for the report, I saw someone mention this in discord a month ago and fixed it, just download the css file again and it will be visible again
