### ISSUE TITLE
v0.1 AfterSherpa+Sherpa Mini

### ISSUE THREAD

**Issue by gargamel778** [eriroh/Mainsail-x-Voron-Toolhead-Theme#5]
Hi, 
Would you be so kind and add a sidebar image for a V0.1 [Mini-AfterSherpa](https://github.com/PrintersForAnts/Mini-AfterSherpa#mini-aftersherpa) with Sherpa Mini?

**Comment by eriroh** [comment]
Added a red version of the mini after sherpa [here](https://github.com/eriroh/Mainsail-x-Voron-Toolhead-Theme/blob/Main/sidebar_toolheads/sidebar-backgroundV0_mini-aftersherpa.png)! Any other color you would like to see?

**Comment by gargamel778** [comment]
That's fantastic! 
It’ll be awesome if you can do one in yellow, this will 100% fit my setup🤩
![392EB56A-B37A-4EA1-9B4A-4D2C4009429E](https://user-images.githubusercontent.com/80474759/187938985-716e5b2e-e01e-4ed6-8123-afd16aab1c52.jpeg)

**Comment by eriroh** [comment]
Fusion doesn't have that bright of a yellow, hope the lighting makes up for that a bit!

**Comment by gargamel778** [comment]
I'll be happy to see any kind of yellow :)

**Comment by gargamel778** [comment]
Thank you @eriroh !!

I love this! Now I know which of my printers I'm controlling 😆


![Untitled 2](https://user-images.githubusercontent.com/80474759/187968768-54362690-57aa-4f03-b8c7-a85ca89bab1b.png)
